// auto generated by @moped/db-pg-migrations - do not edit by hand

import migrations, {MigrationsPackage, operation} from '../';

export {MigrationsPackage};
export default migrations(
  {
    id: 1,
    name: '00001-init.ts',
    operation: async () => operation(await import('./migrations/00001-init')),
  },
  {
    id: 2,
    name: '00002-update.ts',
    operation: async () => operation(await import('./migrations/00002-update')),
  },
);
