const readFileSync = require('fs').readFileSync;
const writeFileSync = require('fs').writeFileSync;
const unlinkSync = require('fs').unlinkSync;
const babel = require('babel-core');
const lsrSync = require('lsr').lsrSync;

const pkg = require(__dirname +
  '/packages/' +
  process.argv[2] +
  '/package.json');
const target = pkg['@moped/target'];

lsrSync(
  __dirname +
    '/packages/' +
    process.argv[2] +
    (target === 'yeoman' ? '/generators' : '/lib'),
).forEach(entry => {
  if (entry.isFile() && /\.jsx?$/.test(entry.path)) {
    const isPublic = /\@public\b/.test(readFileSync(entry.fullPath, 'utf8'));
    writeFileSync(
      entry.fullPath.replace(/\.jsx$/, '.js'),
      babel.transformFileSync(entry.fullPath, {
        babelrc: false,
        presets: [
          target === 'browser'
            ? require.resolve('@moped/babel-preset/browser-commonjs')
            : require.resolve('@moped/babel-preset/server'),
        ],
      }).code,
    );
    if (/\.jsx$/.test(entry.fullPath)) {
      unlinkSync(entry.fullPath);
    }

    const src = readFileSync(
      entry.fullPath.replace(/\.jsx?$/, '.d.ts'),
      'utf8',
    );
    if (isPublic) {
      writeFileSync(
        __dirname +
          '/packages/' +
          process.argv[2] +
          '/' +
          entry.path.substr(2).replace(/\.jsx$/, '.js'),
        "// @autogenerated\n\nmodule.exports = require('./lib/" +
          entry.path.substr(2).replace(/\.jsx?$/, '') +
          "');",
      );
      const lines = [];
      if (/^export [^d]/m.test(src)) {
        // named exports
        lines.push(
          "export * from './lib/" +
            entry.path.substr(2).replace(/\.jsx?$/, '') +
            "';",
        );
      }
      if (/^export default /m.test(src)) {
        // default export
        lines.push(
          "import DEFAULT_EXPORT from './lib/" +
            entry.path.substr(2).replace(/\.jsx?$/, '') +
            "';",
        );
        lines.push('export default DEFAULT_EXPORT;');
      }
      writeFileSync(
        __dirname +
          '/packages/' +
          process.argv[2] +
          '/' +
          entry.path.substr(2).replace(/\.jsx?$/, '.d.ts'),

        '// @autogenerated' +
          (lines.length ? '\n\n' + lines.join('\n') : '') +
          '\n',
      );
    }
  }
});
