// auto generated by @databases/pg-migrations - do not edit by hand

import packageMigrations, {
  MigrationsPackage,
  packageOperation,
} from '@databases/pg-migrations';

export {MigrationsPackage};
export default packageMigrations({
  id: 'd000jcbyi08ktdk0glnc',
  index: 1,
  name: '00001-init.ts',
  operation: async () => packageOperation(await import('./00001-init')),
});
