// Auto generated by @moped/db-schema - do not edit by hand

export default interface DbSessions {
  /**
   * The time that the user logged in.
   */
  created: Date;

  /**
   * Primary Key
   * Default Value: nextval('"Sessions_id_seq"'::regclass)
   */
  id: number;

  /**
   * The time that the user last accessed the web site.
   */
  lastSeen: Date;

  /**
   * The user agent of the browser this session is associated with.
   */
  userAgent: string | null;

  /**
   * The user account that is logged in.
   */
  userID: number;
};
