// generated by ts-bicycle
// do not edit by hand

import Client from 'bicycle/typed-helpers/client';
import OptimisticUpdates from './optimistic';

export default class TypedClient extends Client<OptimisticUpdates> {}
