// Auto generated by @moped/db-schema - do not edit by hand

import sql, {SQLQuery} from '@moped/sql';
import MopedMigrations from './tables/MopedMigrations';

function getOneResult<T>(results: T[]): T | null {
  if (results.length === 0) {
    return null;
  }
  if (results.length === 1) {
    return results[0];
  }
  throw new Error(
    'Expected either one result, or no results to be returned from this query',
  );
}
function noop(): void {}
export interface Connection {
  query(query: SQLQuery): Promise<any[]>;
  task<T>(fn: (connection: Connection) => Promise<T>): Promise<T>;
  tx<T>(fn: (connection: Connection) => Promise<T>): Promise<T>;
}
export class APIBase {
  protected db: Connection;
  constructor(db: Connection) {
    this.db = db;
  }
}

export class MopedMigrationsAPI extends APIBase {
  create(mopedMigrations: {
    id: MopedMigrations['id'];
    isApplied?: MopedMigrations['isApplied'];
    lastDown?: MopedMigrations['lastDown'];
    lastUp?: MopedMigrations['lastUp'];
    name: MopedMigrations['name'];
  }): Promise<MopedMigrations> {
    const columns = Object.keys(mopedMigrations)
      .sort()
      .filter(
        name =>
          name === 'id' ||
          name === 'isApplied' ||
          name === 'lastDown' ||
          name === 'lastUp' ||
          name === 'name',
      )
      .map(name => ({name, value: (mopedMigrations as any)[name]}));
    const data = columns.length
      ? sql`(${sql.join(
          columns.map(c => sql.ident(c.name)),
          ',',
        )}) VALUES (${sql.join(columns.map(c => sql`${c.value}`), ',')})`
      : sql`DEFAULT VALUES`;
    let s = sql`INSERT INTO "MopedMigrations" ${data} RETURNING *;`;
    return this.db.query(s).then(results => results[0]);
  }

  where(query: SQLQuery): Promise<MopedMigrations[]> {
    return this.db.query(
      sql.join([sql`SELECT * FROM "MopedMigrations"`, query], ' WHERE '),
    );
  }

  list(query?: Partial<MopedMigrations>): Promise<MopedMigrations[]> {
    if (query === undefined) {
      return this.db.query(sql`SELECT * FROM "MopedMigrations"`);
    }
    return this.where(
      sql.join(
        Object.keys(query)
          .sort()
          .filter(
            fieldName =>
              fieldName === 'id' ||
              fieldName === 'isApplied' ||
              fieldName === 'lastDown' ||
              fieldName === 'lastUp' ||
              fieldName === 'name',
          )
          .map(field => sql`${sql.ident(field)} = ${(query as any)[field]}`),
        ' AND ',
      ),
    );
  }

  get(
    id: MopedMigrations['id'],
    query?: {
      isApplied?: MopedMigrations['isApplied'];
      lastDown?: MopedMigrations['lastDown'];
      lastUp?: MopedMigrations['lastUp'];
      name?: MopedMigrations['name'];
    },
  ): Promise<MopedMigrations | null> {
    if (query === undefined) {
      return this.db
        .query(sql`SELECT * FROM "MopedMigrations" WHERE "id" = ${id}`)
        .then(getOneResult);
    }
    return this.db
      .query(
        sql.join(
          [sql`SELECT * FROM "MopedMigrations" WHERE "id" = ${id}`].concat(
            Object.keys(query)
              .sort()
              .filter(
                fieldName =>
                  fieldName === 'isApplied' ||
                  fieldName === 'lastDown' ||
                  fieldName === 'lastUp' ||
                  fieldName === 'name',
              )
              .map(
                field => sql`${sql.ident(field)} = ${(query as any)[field]}`,
              ),
          ),
          ' AND ',
        ),
      )
      .then(getOneResult);
  }

  update(
    id: MopedMigrations['id'],
    mopedMigrations: {
      isApplied?: MopedMigrations['isApplied'];
      lastDown?: MopedMigrations['lastDown'];
      lastUp?: MopedMigrations['lastUp'];
      name?: MopedMigrations['name'];
    },
    query?: {
      isApplied?: MopedMigrations['isApplied'];
      lastDown?: MopedMigrations['lastDown'];
      lastUp?: MopedMigrations['lastUp'];
      name?: MopedMigrations['name'];
    },
  ): Promise<void> {
    const updateColumns = sql.join(
      Object.keys(mopedMigrations)
        .sort()
        .filter(
          fieldName =>
            fieldName === 'isApplied' ||
            fieldName === 'lastDown' ||
            fieldName === 'lastUp' ||
            fieldName === 'name',
        )
        .map(
          field =>
            sql`${sql.ident(field)} = ${(mopedMigrations as any)[field]}`,
        ),
      ', ',
    );

    if (query === undefined) {
      return this.db
        .query(
          sql`UPDATE "MopedMigrations" SET ${updateColumns} WHERE "id" = ${id}`,
        )
        .then(noop);
    }
    return this.db
      .query(
        sql.join(
          [
            sql`UPDATE "MopedMigrations" SET ${updateColumns} WHERE "id" = ${id}`,
          ].concat(
            Object.keys(query)
              .sort()
              .filter(
                fieldName =>
                  fieldName === 'isApplied' ||
                  fieldName === 'lastDown' ||
                  fieldName === 'lastUp' ||
                  fieldName === 'name',
              )
              .map(
                field => sql`${sql.ident(field)} = ${(query as any)[field]}`,
              ),
          ),
          ' AND ',
        ),
      )
      .then(noop);
  }

  remove(
    id: MopedMigrations['id'],
    query?: {
      isApplied?: MopedMigrations['isApplied'];
      lastDown?: MopedMigrations['lastDown'];
      lastUp?: MopedMigrations['lastUp'];
      name?: MopedMigrations['name'];
    },
  ): Promise<void> {
    if (!query) {
      return this.db
        .query(sql`DELETE FROM "MopedMigrations" WHERE "id" = ${id}`)
        .then(noop);
    }
    return this.db
      .query(
        sql.join(
          [sql`DELETE FROM "MopedMigrations" WHERE "id" = ${id}`].concat(
            Object.keys(query)
              .sort()
              .filter(
                fieldName =>
                  fieldName === 'isApplied' ||
                  fieldName === 'lastDown' ||
                  fieldName === 'lastUp' ||
                  fieldName === 'name',
              )
              .map(
                field => sql`${sql.ident(field)} = ${(query as any)[field]}`,
              ),
          ),
          ' AND ',
        ),
      )
      .then(noop);
  }
}

export default class Database extends APIBase {
  private _MopedMigrations: MopedMigrationsAPI | void;

  get MopedMigrations(): MopedMigrationsAPI {
    return (
      this._MopedMigrations ||
      (this._MopedMigrations = new MopedMigrationsAPI(this.db))
    );
  }

  task<T>(fn: (connection: Database) => Promise<T>): Promise<T> {
    return this.db.task(db => fn(new Database(db)));
  }
  tx<T>(fn: (connection: Database) => Promise<T>): Promise<T> {
    return this.db.tx(db => fn(new Database(db)));
  }
}
