// Auto generated by @moped/db-schema - do not edit by hand

export default interface Dbnumbers {
  /**
   * Primary Key
   * Default Value: nextval('numbers_id_seq'::regclass)
   */
  id: number;
  value: number;
};
